### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by professionaldumbass1337** [jakob-he/string-kernel#1]
> Traceback (most recent call last):
  File "G:\\uf022Research R&E\ml_proteinSequencePrediction_test0.py", line 1, in <module>
    from strkernel.mismatch_kernel import MismatchKernel
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\strkernel\mismatch_kernel.py", line 12, in <module>
    from strkernel.lib.mismatchTrie import MismatchTrie
ModuleNotFoundError: No module named 'strkernel.lib.mismatchTrie'

I got this message simply from importing the Mismatch Kernel

This is the import line:
`from strkernel.mismatch_kernel import MismatchKernel
from strkernel.mismatch_kernel import preprocess
...`

I installed the package correctly using pip in command promt

**Comment by professionaldumbass1337** [comment]
The MismatchTrie.py file was named wrong, change to mismatchTrie.py
